name: Manual rebuild
on:
  [workflow_dispatch]

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      IMG_DATE: ${{ steps.date.outputs.IMG_DATE }}
    steps:
      - name: Get current date in RFC 3339
        id: date
        run: |
          IMG_DATE=$(date --rfc-3339=seconds | sed 's/ /T/')
          echo "IMG_DATE=${IMG_DATE}" >> $GITHUB_OUTPUT
          echo "The date is $IMG_DATE"

  get-version:
    runs-on: ubuntu-latest
    outputs:
      PKG_VER: ${{ steps.version.outputs.PKG_VER }}
    steps:
      - name: Add package source to APT
        run: |
          curl -vSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo apt-get update

      - name: Get package version
        id: version
        run: |
          PKG_VER=$(apt list microsoft-edge-stable | awk -F'[ /]' '/microsoft-edge-stable/ {print $3}')
          echo "PKG_VER=${PKG_VER}" >> $GITHUB_OUTPUT
          echo "The package version is $PKG_VER"

  rebuild:
    runs-on: ubuntu-latest
    needs: [get-date, get-version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tibor309
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          build-args: |
            IMAGE_BUILD_DATE=${{ needs.get-date.outputs.IMG_DATE }}
          tags: |
            ghcr.io/tibor309/edge:latest
            ghcr.io/tibor309/edge:stable
            ghcr.io/tibor309/edge:${{ needs.get-version.outputs.PKG_VER }}
