name: Scheduled build - dev
on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  get-version-dev:
    runs-on: ubuntu-latest
    outputs:
      PKG_VER: ${{ steps.getver.outputs.PKG_VER }}
    steps:
      - name: Add package source to APT
        run: |
          curl -vSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo apt-get update

      - name: Get package version
        id: getver
        run: |
          PKG_VER=$(apt list microsoft-edge-dev | awk -F'[ /]' '/microsoft-edge-dev/ {print $3}')
          echo "PKG_VER=${PKG_VER}" >> $GITHUB_OUTPUT
          echo "The package version is $PKG_VER"

  rebuild-dev:
    runs-on: ubuntu-latest
    needs: get-version-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'dev'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tibor309
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image for amd64/arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/tibor309/edge:dev
            ghcr.io/tibor309/edge:${{ needs.get-version-dev.outputs.PKG_VER }}